---

# Use cautiously!

- hosts: all
  gather_facts: true
  become: yes
  become_user: root

  tasks:

    - name: Run RKE2 Uninstall
      shell: "/usr/local/bin/rke2-uninstall.sh"

    - name: Wipe longhorn
      shell: "rm -Rf /var/lib/longhorn/*"

    - name: Reboot
      reboot:
        reboot_timeout: 600
