---

- hosts: all
  become: yes

  vars:
    systemd_package: nginx

  tasks:

    - name: Install packages
      package:
        name: 
          - "{{ systemd_package }}"
        state: present

    - name: Restart service; also issue daemon-reload to pick up config changes
      systemd:
        enabled: yes
        state: restarted
        daemon_reload: yes
        name: "{{ systemd_package }}"
